appName: Servicename
appIamge: gcr.io/google-samples/microservices-demo/servicename:v0.10.1
appVersion: v0.0.0
appReplicas: 1
containerPort: 8080
containerEnvVars: 
  - name: ENV_VAR_ONE
    value: "valueone"
  - name: ENV_VAR_TWO
    value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP